server:
  port: 8080

logging:
  level:
    org:
      springdoc: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

client-openai-key: ${API_KEY}
client-openai-endpoint: ${API_URI}
client-openai-deployment-name: gpt-35-turbo
prompt-execution-settings-temperature: 0.7